{
 "title": "IPFS Monitoring",
 "description": "IPFS monitoring with Prometheus",
 "tags": [
  "IPFS",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "up{job=\"ipfs-cluster|ipfs-peer\"}"
   },
   { "name": "service", "label": "service", "query": "v.ipfs.team,cluster,gateway" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1s",
     "expr": "sum(ipfs_p2p_peers_total{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22ipfs_p2p_peers_total%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-12-11%200%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Number of peerings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ipfs_p2p_peers_total{instance=~\".*($service).*\",instance=~\"$instance\"}) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "go_goroutines{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22go_goroutines%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%22%2C%22range_input%22%3A%22604801s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "irate(process_cpu_seconds_total{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}[5m]) * 1000",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22rate(process_cpu_seconds_total%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%5B1m%5D)%20*%201000%22%2C%22range_input%22%3A%22604800s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "go_memstats_alloc_bytes{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"} / 1024 / 1024",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22process_resident_memory_bytes%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%20%2F%201024%20%2F%201024%22%2C%22range_input%22%3A%22604800s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_open_fds{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22go_goroutines%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%22%2C%22range_input%22%3A%22604801s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "irate(go_gc_duration_seconds_sum{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22rate(go_gc_duration_seconds_count%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%5B1m%5D)%20*%201000%22%2C%22range_input%22%3A%22604800s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Wantlist length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "ipfs_bitswap_wantlist_total{job=~\"ipfs-cluster|ipfs-peer\",instance=~\".*($service).*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "/prometheus/graph#%5B%7B%22expr%22%3A%22process_resident_memory_bytes%7Bjob%3D~%5C%22gateway%7Cstorage%5C%22%7D%20%2F%201024%20%2F%201024%22%2C%22range_input%22%3A%22604800s%22%2C%22end_input%22%3A%222015-11-26%204%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}